### ISSUE TITLE
R sessions not terminated with paralleStop in multicore mode

### ISSUE THREAD

**Issue by pazthy** [mlr-org/parallelMap#55]
We are running parallelMap with som mlr functions in the structure:
```r
parallelStartMulticore(parallel::detectCores())

l_ply(seq(100),function(x){


makeResampleDesc

...

}

)
parallelStop()
```
We observe that not all the R processes are stopped in some of the iterations, and at the end of the 100 iterations we have a number of R processes that do not terminate.

**Comment by jakob-r** [comment]
Can you provide a minimal working example? Did you activate parallelism in plyr?

**Comment by pat-s** [comment]
Hi,
in this case we need a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), preferably using the [reprex](https://github.com/tidyverse/reprex) package.

Since this issue is already more than 1 year old and we had no similar complains, I'll close here.
